version: "3"
services:
  centos7:
    container_name: 'centos7'
    stdin_open: true
    tty: true
    image: centos:centos7.9.2009
    command: top
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ubuntu-python
    container_name: 'ubuntu'
    stdin_open: true
    tty: true
    command: bash
  fedora:
    container_name: 'fedora'
    stdin_open: true
    tty: true
    image: pycontribs/fedora:latest
    command: bash